version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=dynamodb,sns 
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"  # Puerto para la API de LocalStack
      - "8080:8000"  # Puerto específico para DynamoDB, si lo prefieres
    volumes:
      - "./localstack:/var/lib/localstack"  # Persistencia de datos
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    ports:
      - "8081:8001"  # Puerto para la UI de DynamoDB Admin
    depends_on:
      - localstack

